---
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
        key_url: 'https://packages.chef.io/chef.asc'
    packages:
      - chefdk

before_script:
  - eval "$(chef shell-init bash)"
  - chef exec bundle install --with unit,smoke,travis

script:
  # Print versions
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - kitchen --version
  # Run style checks
  - chef exec cookstyle
  - chef exec foodcritic --rule-file .foodcritic .
  # Run unit tests
  - chef exec rspec
