---
dist: trusty

install:
  - bundle install --with unit,travis

script:
  # Print versions
  - bundle exec cookstyle --version
  - bundle exec foodcritic --version
  # Run style checks
  - bundle exec cookstyle
  - bundle exec foodcritic --rule-file .foodcritic .
  # Run unit tests
  - bundle exec rspec
